language: python
sudo: false
python:
  - 3.6
cache: pip
install:
  - pip install flake8
  - pip install -r requirements.txt
  - python setup.py install
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - flake8 pyfod
  - coverage run --source=QUAD -m unittest discover -s "test" -p "test*.py"
  - coverage report --fail-under=50
notifications:
  email: 
    - prmiles@ncsu.edu
    - rabrough@ncsu.edu
after_success:
  - coveralls
